<a href="https://colab.research.google.com/github/Tatiana1778/Nutritional_planner_AI/blob/main/AI_project_nutrition_food_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt # for data visualization purposes
import seaborn as sns # for statistical data visualization
%matplotlib inline

In [ ]:

dataset = pd.read_csv("/content/sample_data/food_dataset.csv", delimiter=';')
dataset.head(5)

,Index,Food category,Type of food,Allergens,Food,Caloric Value (kcal),Fat (g),Saturated Fats (g),Monounsaturated Fats (g),Polyunsaturated Fats (g),...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,1,meat,pork,NaN,Pork Loin (cooked),213,12,5,5,1,...,15,0,1,27,0,225,380,30,3,57
1,2,meat,chicken,NaN,Chicken Wing (cooked),52,4,1,1,1,...,15,0,1,20,0,150,230,20,3,11
2,3,meat,chicken,NaN,Chicken Back (cooked),93,7,2,3,1,...,20,0,1,22,0,180,250,22,3,21
3,4,meat,chicken,NaN,Chicken Leg (fried),431,26,6,10,6,...,30,0,2,35,0,290,400,40,5,105
4,5,meat,turkey,NaN,Turkey Steak (fried),179,11,3,4,3,...,25,0,1,30,0,200,300,35,4,41

# Data Cleanup

In [ ]:
col_names = ['Index','Food_category','Type_of_food','Allergens','Food','Caloric Value (kcal)', 'Fat (g)','Saturated Fats (g)','Monounsaturated Fats (g)', 'Polyunsaturated Fats (g)','Carbohydrates (g)','Sugars (g)','Protein (g)','Dietary Fiber (g)','Cholesterol (mg)','Sodium (mg)','Water (g)','Vitamin A (IU)','Vitamin B1 (mg)','Vitamin B11 (mcg)','Vitamin B12 (mcg)','Vitamin B2 (mg)', 'Vitamin B3 (mg)','Vitamin B5 (mg)','Vitamin B6','Vitamin C','Vitamin D','Vitamin E','Vitamin K','Calcium','Copper','Iron','Magnesium','Manganese','Phosphorus', 'Potassium', 'Selenium', 'Zinc', 'Nutrition Density']

dataset.columns = col_names
dataset.columns

Index(['Index', 'Food_category', 'Type_of_food', 'Allergens', 'Food',
       'Caloric Value (kcal)', 'Fat (g)', 'Saturated Fats (g)',
       'Monounsaturated Fats (g)', 'Polyunsaturated Fats (g)',
       'Carbohydrates (g)', 'Sugars (g)', 'Protein (g)', 'Dietary Fiber (g)',
       'Cholesterol (mg)', 'Sodium (mg)', 'Water (g)', 'Vitamin A (IU)',
       'Vitamin B1 (mg)', 'Vitamin B11 (mcg)', 'Vitamin B12 (mcg)',
       'Vitamin B2 (mg)', 'Vitamin B3 (mg)', 'Vitamin B5 (mg)', 'Vitamin B6',
       'Vitamin C', 'Vitamin D', 'Vitamin E', 'Vitamin K', 'Calcium', 'Copper',
       'Iron', 'Magnesium', 'Manganese', 'Phosphorus', 'Potassium', 'Selenium',
       'Zinc', 'Nutrition Density'],
      dtype='object')

In [ ]:
# view summary of dataset

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 39 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Index                     300 non-null    int64
 1   Food_category             300 non-null    object
 2   Type_of_food              300 non-null    object
 3   Allergens                 123 non-null    object
 4   Food                      300 non-null    object
 5   Caloric Value (kcal)      300 non-null    int64
 6   Fat (g)                   300 non-null    int64
 7   Saturated Fats (g)        300 non-null    int64
 8   Monounsaturated Fats (g)  300 non-null    int64
 9   Polyunsaturated Fats (g)  300 non-null    int64
 10  Carbohydrates (g)         300 non-null    int64
 11  Sugars (g)                300 non-null    int64
 12  Protein (g)               300 non-null    int64
 13  Dietary Fiber (g)         300 non-null    int64
 14  Cholesterol (mg)          300 non-null    int64
 15  Sodium (mg)               300 non-null    int64
 16  Water (g)                 300 non-null    int64
 17  Vitamin A (IU)            300 non-null    int64
 18  Vitamin B1 (mg)           300 non-null    int64
 19  Vitamin B11 (mcg)         300 non-null    int64
 20  Vitamin B12 (mcg)         300 non-null    int64
 21  Vitamin B2 (mg)           300 non-null    int64
 22  Vitamin B3 (mg)           300 non-null    int64
 23  Vitamin B5 (mg)           300 non-null    int64
 24  Vitamin B6                300 non-null    int64
 25  Vitamin C                 300 non-null    int64
 26  Vitamin D                 300 non-null    int64
 27  Vitamin E                 300 non-null    int64
 28  Vitamin K                 300 non-null    int64
 29  Calcium                   300 non-null    int64
 30  Copper                    300 non-null    int64
 31  Iron                      300 non-null    int64
 32  Magnesium                 300 non-null    int64
 33  Manganese                 300 non-null    int64
 34  Phosphorus                300 non-null    int64
 35  Potassium                 300 non-null    int64
 36  Selenium                  300 non-null    int64
 37  Zinc                      300 non-null    int64
 38  Nutrition Density         300 non-null    int64
dtypes: int64(35), object(4)
memory usage: 91.5+ KB

In [ ]:
# view dimensions of dataset
dataset.shape

(300, 39)

In [ ]:
# find categorical variables

categorical = [var for var in dataset.columns if dataset[var].dtype=='O']

print('There are {} categorical variables\n'.format(len(categorical)))

print('The categorical variables are :\n\n', categorical)

There are 4 categorical variables

The categorical variables are :

 ['Food_category', 'Type_of_food', 'Allergens', 'Food']

In [ ]:
# view the categorical variables

dataset[categorical].tail(10)

    Food_category       Type_of_food  Allergens                       Food
290        pastry       sweet pastry     Gluten                     waffle
291        pastry       sweet pastry     Gluten                   pancakes
292        pastry       sweet pastry     Gluten                     muffin
293        pastry       sweet pastry     Gluten                      donut
294     sweetener  natural sweetener        NaN                      honey
295  fruit spread    Fruit preserves        NaN                  fruit jam
296        spread         Nut butter  Tree nuts  chocolate hazelnut spread
297        spread         Nut butter    Peanuts              peanut butter
298  fruit spread    Fruit preserves        NaN           orange marmalade
299  fruit spread    Fruit preserves        NaN                apricot jam

In [ ]:
# check labels in region variable
dataset['Type_of_food'] = dataset['Type_of_food'].str.lower()
dataset.Type_of_food.unique()

array(['pork', 'chicken', 'turkey', 'duck', 'quail', 'goose', 'emu',
       'ostrich', 'beef', 'ham', 'lamb', 'bacon', 'whitefish', 'carp',
       'wolffish', 'snapper', 'roe', 'whiting', 'salmon', 'american',
       'shark', 'jellyfish', 'halibut', 'cuttlefish', 'spot', 'salt',
       'mackerel', 'scup', 'herring', 'sablefish', 'pink', 'northern',
       'mullet', 'sea', 'sturgeon', 'dolphinfish', 'crayfish', 'perch',
       'eel', 'caviar', 'bluefish', 'rockfish', 'swordfish', 'sardine',
       'anchovy', 'sardines', 'tuna', 'eastern', 'shrimp', 'squid',
       'oyster', 'blue', 'clams', 'lobster', 'haddock', 'pasta', 'rice',
       'noodles', 'spaghetti', 'bread', 'tortilla', 'potato', 'tomato',
       'cardoon', 'spinach', 'kale', 'carrot', 'lotus root', 'corn',
       'radish', 'lettuce', 'avocado', 'peas', 'beet', 'chili pepper',
       'artichoke', 'onion', 'cabbage', 'parsnip', 'pepper', 'mushrooms',
       'soy', 'cranberrys', 'vinegar', 'honey, neng', 'tomato, mashrooms',
       'fish (anchovies)', 'cheese', 'egg', 'plant-based protein',
       'bean product', 'bean', 'soybean', 'pulse', 'nut oil',
       'nut butter', 'spice oil', 'animal fat', 'vegetable oil',
       'seed oil', 'fruit oil', 'tropical oil', 'fruit', 'sweet pastry',
       'natural sweetener', 'fruit preserves'], dtype=object)

In [ ]:
# check missing values in categorical variables

dataset[categorical].isnull().sum()

Food_category      0
Type_of_food       0
Allergens        177
Food               0
dtype: int64

In [ ]:
# view frequency counts of values in categorical variables

for var in categorical:
    print(dataset[var].value_counts())

Food_category
fruit           69
seafood         55
grain           32
vegetable       31
meat            30
Legume          26
diary           15
oil             14
sauce           11
protein          4
pastry           4
spread           3
fruit spread     3
fat              2
sweetener        1
Name: count, dtype: int64
Type_of_food
fruit        69
bean         21
bread        15
cheese       15
chicken       7
             ..
clams         1
blue          1
squid         1
jellyfish     1
lobster       1
Name: count, Length: 106, dtype: int64
Allergens
Fish                     55
Dairy                    14
Gluten                   13
Gluten, Soy               9
Soy                       9
Gluten, Soy, Dairy        5
Tree nuts                 3
Eggs                      3
Sesame                    2
Egg, Gluten               1
Mustard                   1
Cheese                    1
Gluten, Corn              1
Dairy (if milk added)     1
Gluten, Dairy, Soy        1
Gluten, Oats              1
Eggs, Gluten              1
Corn, Gluten              1
Peanuts                   1
Name: count, dtype: int64
Food
Pork Loin (cooked)           1
nutmeg butter oil            1
hazelnut oil                 1
yardlong beans cooked        1
yellow snap beans cooked     1
                            ..
white bread                  1
spinach spaghetti dry        1
rice noodles dry             1
japanese soba noodles dry    1
apricot jam                  1
Name: count, Length: 300, dtype: int64

In [ ]:
# view frequency distribution of categorical variables

for var in categorical:
    # Use float(len(dataset)) instead of np.float(len(dataset))
    print(dataset[var].value_counts() / float(len(dataset)))

Food_category
fruit           0.230000
seafood         0.183333
grain           0.106667
vegetable       0.103333
meat            0.100000
Legume          0.086667
diary           0.050000
oil             0.046667
sauce           0.036667
protein         0.013333
pastry          0.013333
spread          0.010000
fruit spread    0.010000
fat             0.006667
sweetener       0.003333
Name: count, dtype: float64
Type_of_food
fruit        0.230000
bean         0.070000
bread        0.050000
cheese       0.050000
chicken      0.023333
               ...
clams        0.003333
blue         0.003333
squid        0.003333
jellyfish    0.003333
lobster      0.003333
Name: count, Length: 106, dtype: float64
Allergens
Fish                     0.183333
Dairy                    0.046667
Gluten                   0.043333
Gluten, Soy              0.030000
Soy                      0.030000
Gluten, Soy, Dairy       0.016667
Tree nuts                0.010000
Eggs                     0.010000
Sesame                   0.006667
Egg, Gluten              0.003333
Mustard                  0.003333
Cheese                   0.003333
Gluten, Corn             0.003333
Dairy (if milk added)    0.003333
Gluten, Dairy, Soy       0.003333
Gluten, Oats             0.003333
Eggs, Gluten             0.003333
Corn, Gluten             0.003333
Peanuts                  0.003333
Name: count, dtype: float64
Food
Pork Loin (cooked)           0.003333
nutmeg butter oil            0.003333
hazelnut oil                 0.003333
yardlong beans cooked        0.003333
yellow snap beans cooked     0.003333
                               ...
white bread                  0.003333
spinach spaghetti dry        0.003333
rice noodles dry             0.003333
japanese soba noodles dry    0.003333
apricot jam                  0.003333
Name: count, Length: 300, dtype: float64

In [ ]:

# check frequency distribution of values in region variable

dataset.Type_of_food.value_counts()

Type_of_food
fruit        69
bean         21
bread        15
cheese       15
chicken       7
             ..
clams         1
blue          1
squid         1
jellyfish     1
lobster       1
Name: count, Length: 106, dtype: int64

In [ ]:
dataset[['Type_of_food','Caloric Value (kcal)']]

        Type_of_food  Caloric Value (kcal)
0               pork                   213
1            chicken                    52
2            chicken                    93
3            chicken                   431
4             turkey                   179
..               ...                   ...
295  fruit preserves                    56
296       nut butter                   100
297       nut butter                    88
298  fruit preserves                    49
299  fruit preserves                    48

[300 rows x 2 columns]

In [ ]:
# find numerical variables

numerical = [var for var in dataset.columns if dataset[var].dtype!='O']

print('There are {} numerical variables\n'.format(len(numerical)))

print('The numerical variables are :', numerical)

There are 35 numerical variables

The numerical variables are : ['Index', 'Caloric Value (kcal)', 'Fat (g)', 'Saturated Fats (g)', 'Monounsaturated Fats (g)', 'Polyunsaturated Fats (g)', 'Carbohydrates (g)', 'Sugars (g)', 'Protein (g)', 'Dietary Fiber (g)', 'Cholesterol (mg)', 'Sodium (mg)', 'Water (g)', 'Vitamin A (IU)', 'Vitamin B1 (mg)', 'Vitamin B11 (mcg)', 'Vitamin B12 (mcg)', 'Vitamin B2 (mg)', 'Vitamin B3 (mg)', 'Vitamin B5 (mg)', 'Vitamin B6', 'Vitamin C', 'Vitamin D', 'Vitamin E', 'Vitamin K', 'Calcium', 'Copper', 'Iron', 'Magnesium', 'Manganese', 'Phosphorus', 'Potassium', 'Selenium', 'Zinc', 'Nutrition Density']

In [ ]:
# view the numerical variables

dataset[numerical].head()

,Index,Caloric Value (kcal),Fat (g),Saturated Fats (g),Monounsaturated Fats (g),Polyunsaturated Fats (g),Carbohydrates (g),Sugars (g),Protein (g),Dietary Fiber (g),...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
0,1,213,12,5,5,1,0,0,24,0,...,15,0,1,27,0,225,380,30,3,57
1,2,52,4,1,1,1,0,0,5,0,...,15,0,1,20,0,150,230,20,3,11
2,3,93,7,2,3,1,0,0,8,0,...,20,0,1,22,0,180,250,22,3,21
3,4,431,26,6,10,6,14,0,34,1,...,30,0,2,35,0,290,400,40,5,105
4,5,179,11,3,4,3,11,0,9,0,...,25,0,1,30,0,200,300,35,4,41

In [ ]:
# check missing values in numerical variables

dataset[numerical].isnull().sum()

Index                       0
Caloric Value (kcal)        0
Fat (g)                     0
Saturated Fats (g)          0
Monounsaturated Fats (g)    0
Polyunsaturated Fats (g)    0
Carbohydrates (g)           0
Sugars (g)                  0
Protein (g)                 0
Dietary Fiber (g)           0
Cholesterol (mg)            0
Sodium (mg)                 0
Water (g)                   0
Vitamin A (IU)              0
Vitamin B1 (mg)             0
Vitamin B11 (mcg)           0
Vitamin B12 (mcg)           0
Vitamin B2 (mg)             0
Vitamin B3 (mg)             0
Vitamin B5 (mg)             0
Vitamin B6                  0
Vitamin C                   0
Vitamin D                   0
Vitamin E                   0
Vitamin K                   0
Calcium                     0
Copper                      0
Iron                        0
Magnesium                   0
Manganese                   0
Phosphorus                  0
Potassium                   0
Selenium                    0
Zinc                        0
Nutrition Density           0
dtype: int64

#Split Data into Training & Testing datasets

In [ ]:
X = dataset.drop(['Caloric Value (kcal)'], axis=1) #x has dropped calories

y = dataset['Caloric Value (kcal)'] #y has just calories and every other are droppped

In [ ]:
# split X and y into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
dataset.shape

(300, 39)

In [ ]:
y_train

134      8
145    114
63     182
293    192
285     97
      ...
251     64
192    241
117    161
47     755
172     80
Name: Caloric Value (kcal), Length: 240, dtype: int64

In [ ]:
# check the shape of X_train and X_test

X_train.shape, X_test.shape

((240, 38), (60, 38))

#Further Data Processing

In [ ]:
# check data types in X_train

X_train.dtypes

Index                        int64
Food_category               object
Type_of_food                object
Allergens                   object
Food                        object
Fat (g)                      int64
Saturated Fats (g)           int64
Monounsaturated Fats (g)     int64
Polyunsaturated Fats (g)     int64
Carbohydrates (g)            int64
Sugars (g)                   int64
Protein (g)                  int64
Dietary Fiber (g)            int64
Cholesterol (mg)             int64
Sodium (mg)                  int64
Water (g)                    int64
Vitamin A (IU)               int64
Vitamin B1 (mg)              int64
Vitamin B11 (mcg)            int64
Vitamin B12 (mcg)            int64
Vitamin B2 (mg)              int64
Vitamin B3 (mg)              int64
Vitamin B5 (mg)              int64
Vitamin B6                   int64
Vitamin C                    int64
Vitamin D                    int64
Vitamin E                    int64
Vitamin K                    int64
Calcium                      int64
Copper                       int64
Iron                         int64
Magnesium                    int64
Manganese                    int64
Phosphorus                   int64
Potassium                    int64
Selenium                     int64
Zinc                         int64
Nutrition Density            int64
dtype: object

In [ ]:
# display categorical variables

categorical = [col for col in X_train.columns if X_train[col].dtypes == 'O']

categorical

['Food_category', 'Type_of_food', 'Allergens', 'Food']

In [ ]:
# display numerical variables

numerical = [col for col in X_train.columns if X_train[col].dtypes != 'O']

numerical

['Index',
 'Fat (g)',
 'Saturated Fats (g)',
 'Monounsaturated Fats (g)',
 'Polyunsaturated Fats (g)',
 'Carbohydrates (g)',
 'Sugars (g)',
 'Protein (g)',
 'Dietary Fiber (g)',
 'Cholesterol (mg)',
 'Sodium (mg)',
 'Water (g)',
 'Vitamin A (IU)',
 'Vitamin B1 (mg)',
 'Vitamin B11 (mcg)',
 'Vitamin B12 (mcg)',
 'Vitamin B2 (mg)',
 'Vitamin B3 (mg)',
 'Vitamin B5 (mg)',
 'Vitamin B6',
 'Vitamin C',
 'Vitamin D',
 'Vitamin E',
 'Vitamin K',
 'Calcium',
 'Copper',
 'Iron',
 'Magnesium',
 'Manganese',
 'Phosphorus',
 'Potassium',
 'Selenium',
 'Zinc',
 'Nutrition Density']

In [ ]:
# print percentage of missing values in the categorical variables in training set

X_train[categorical].isnull().mean()

Food_category    0.000000
Type_of_food     0.000000
Allergens        0.570833
Food             0.000000
dtype: float64

In [ ]:
# print categorical variables with missing data

for col in categorical:
    if X_train[col].isnull().mean()>0:
        print(col, (X_train[col].isnull().mean()),2)

Allergens 0.5708333333333333 2

In [ ]:
# impute missing categorical variables with most frequent value

for df2 in [X_train, X_test]:
    df2['Allergens'].fillna(X_train['Allergens'].mode()[0], inplace=True)

<ipython-input-244-e6ccb3f716e5>:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Allergens'].fillna(X_train['Allergens'].mode()[0], inplace=True)

In [ ]:
# check missing values in categorical variables in X_train

X_train[categorical].isnull().sum()

Food_category    0
Type_of_food     0
Allergens        0
Food             0
dtype: int64

In [ ]:
# check missing values in categorical variables in X_test

X_test[categorical].isnull().sum()

Food_category    0
Type_of_food     0
Allergens        0
Food             0
dtype: int64

In [ ]:
# check missing values in X_train

X_train.isnull().sum()

Index                       0
Food_category               0
Type_of_food                0
Allergens                   0
Food                        0
Fat (g)                     0
Saturated Fats (g)          0
Monounsaturated Fats (g)    0
Polyunsaturated Fats (g)    0
Carbohydrates (g)           0
Sugars (g)                  0
Protein (g)                 0
Dietary Fiber (g)           0
Cholesterol (mg)            0
Sodium (mg)                 0
Water (g)                   0
Vitamin A (IU)              0
Vitamin B1 (mg)             0
Vitamin B11 (mcg)           0
Vitamin B12 (mcg)           0
Vitamin B2 (mg)             0
Vitamin B3 (mg)             0
Vitamin B5 (mg)             0
Vitamin B6                  0
Vitamin C                   0
Vitamin D                   0
Vitamin E                   0
Vitamin K                   0
Calcium                     0
Copper                      0
Iron                        0
Magnesium                   0
Manganese                   0
Phosphorus                  0
Potassium                   0
Selenium                    0
Zinc                        0
Nutrition Density           0
dtype: int64

In [ ]:
# check missing values in X_test

X_test.isnull().sum()

Index                       0
Food_category               0
Type_of_food                0
Allergens                   0
Food                        0
Fat (g)                     0
Saturated Fats (g)          0
Monounsaturated Fats (g)    0
Polyunsaturated Fats (g)    0
Carbohydrates (g)           0
Sugars (g)                  0
Protein (g)                 0
Dietary Fiber (g)           0
Cholesterol (mg)            0
Sodium (mg)                 0
Water (g)                   0
Vitamin A (IU)              0
Vitamin B1 (mg)             0
Vitamin B11 (mcg)           0
Vitamin B12 (mcg)           0
Vitamin B2 (mg)             0
Vitamin B3 (mg)             0
Vitamin B5 (mg)             0
Vitamin B6                  0
Vitamin C                   0
Vitamin D                   0
Vitamin E                   0
Vitamin K                   0
Calcium                     0
Copper                      0
Iron                        0
Magnesium                   0
Manganese                   0
Phosphorus                  0
Potassium                   0
Selenium                    0
Zinc                        0
Nutrition Density           0
dtype: int64

In [ ]:
# print categorical variables

categorical

['Food_category', 'Type_of_food', 'Allergens', 'Food']

In [ ]:
X_train[categorical].head()

    Food_category  Type_of_food Allergens                 Food
134     vegetable       lettuce      Fish      romaine lettuce
145     vegetable       parsnip      Fish      parsnips cooked
63        seafood     swordfish      Fish     swordfish cooked
293        pastry  sweet pastry    Gluten                donut
285         fruit         fruit      Fish  blackberries frozen

#Encode Categorical Data into Numbers

In [ ]:
# import category encoders
!pip install category_encoders
from sklearn import preprocessing
import category_encoders as ce
encoder = ce.OneHotEncoder(cols=['Type_of_food', 'Food_category', 'Allergens','Food'])

Requirement already satisfied: category_encoders in /usr/local/lib/python3.10/dist-packages (2.6.4)
Requirement already satisfied: numpy>=1.14.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.26.4)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.5.2)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.13.1)
Requirement already satisfied: statsmodels>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (0.14.4)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (2.2.2)
Requirement already satisfied: patsy>=0.5.1 in /usr/local/lib/python3.10/dist-packages (from category_encoders) (1.0.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=1.0.5->category_encoders) (2024.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=0.20.0->category_encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/dist-packages (from statsmodels>=0.9.0->category_encoders) (24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)

In [ ]:
# encode remaining variables with one-hot encoding

X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)

ValueError: X does not contain the columns listed in cols

In [ ]:
X_train.head()

,Index,Food_category_1,Food_category_2,Food_category_3,Food_category_4,Food_category_5,Food_category_6,Food_category_7,Food_category_8,Food_category_9,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
134,135,1,0,0,0,0,0,0,0,0,...,16,0,1,7,0,14,116,0,0,21
145,146,1,0,0,0,0,0,0,0,0,...,0,59,0,1,46,1,110,587,0,37
63,64,0,1,0,0,0,0,0,0,0,...,0,6,0,1,37,0,322,529,0,34
293,294,0,0,1,0,0,0,0,0,0,...,27,0,1,8,0,53,46,0,0,64
285,286,0,0,0,1,0,0,0,0,0,...,44,0,1,33,2,45,211,0,0,83

In [ ]:
X_train.shape

(240, 52)

In [ ]:
X_test.head()

,Index,Food_category_1,Food_category_2,Food_category_3,Food_category_4,Food_category_5,Food_category_6,Food_category_7,Food_category_8,Food_category_9,...,Calcium,Copper,Iron,Magnesium,Manganese,Phosphorus,Potassium,Selenium,Zinc,Nutrition Density
208,209,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
188,189,0,0,0,0,0,0,0,1,0,...,0,211,0,2,86,1,84,690,0,48
12,13,0,0,0,0,0,1,0,0,0,...,15,0,1,24,0,180,270,28,3,121
221,222,0,0,0,1,0,0,0,0,0,...,0,9,0,0,14,0,39,302,0,21
239,240,0,0,0,1,0,0,0,0,0,...,0,74,0,0,18,0,26,333,0,28

In [ ]:
X_test.shape

(60, 52)

In [ ]:
cols = X_train.columns

In [ ]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

ValueError: could not convert string to float: 'lettuce'

In [ ]:
X_train = pd.DataFrame(X_train, columns=[cols])

In [ ]:
X_test = pd.DataFrame(X_test, columns=[cols])



```
# This is formatted as code
```

#Train on Training Data

In [ ]:
# train a Gaussian Naive Bayes classifier on the training set
from sklearn.naive_bayes import GaussianNB
#from sklearn.neighbors import KNeighborsClassifier

# instantiate the model
gnb = GaussianNB()
#gnb = KNeighborsClassifier(3)


# fit the model
gnb.fit(X_train, y_train)

#Predict Y based on X variables

In [ ]:
y_pred = gnb.predict(X_test)

y_pred

#Determine Accuracy

In [ ]:
from sklearn.metrics import accuracy_score

print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

In [ ]:
y_pred_train = gnb.predict(X_train)

y_pred_train

In [ ]:
print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

#Run Predictions on Test Data

In [ ]:
# print the scores on training and test set

print('Training set score: {:.4f}'.format(gnb.score(X_train, y_train)))

print('Test set score: {:.4f}'.format(gnb.score(X_test, y_test)))

#Accuracy

In [ ]:
# check class distribution in test set

y_test.value_counts()

In [ ]:
# check null accuracy score

null_accuracy = (7407/(7407+2362))

print('Null accuracy score: {0:0.4f}'. format(null_accuracy))